### ISSUE TITLE
Presence sensor publisher is not working

### ISSUE THREAD

**Issue by machinekoder** [cyberbotics/webots_ros#8]
For some reason, the presence sensor publisher is not working for me.

I tried to enable the presence sensor via ROS service call and subscribing to the ROS topic. However, I can't get it to work. I also verified that the connector is not the problem using a Python-based robot controller.

Any ideas on how to debug the problem?

**Comment by DavidMansolino** [comment]
Do you have any example simulation world that you can share where this happens?

**Comment by DavidMansolino** [comment]
I just tried with the connector sample (https://cyberbotics.com/doc/guide/samples-devices#connector-wbt).
I assigned the ros controller to the first robot (light blue) and then start the simulation and enable the presence and then display it's value with ros client interface:
```
rosservice call /MyBot_1_9937_cyberbotics_david/connector/presence_sensor/enable "{enable: 1}"
rostopic echo /MyBot_1_9937_cyberbotics_david/connector/presence
```

This is the output:
```
header: 
  seq: 0
  stamp: 
    secs: 1570027899
    nsecs: 104240062
  frame_id: "MyBot_1_9937_cyberbotics_david/connector"
data: 0
---
header: 
  seq: 0
  stamp: 
    secs: 1570027916
    nsecs: 347240245
  frame_id: "MyBot_1_9937_cyberbotics_david/connector"
data: 1
---
header: 
  seq: 0
  stamp: 
    secs: 1570027916
    nsecs: 707253983
  frame_id: "MyBot_1_9937_cyberbotics_david/connector"
data: 0
---
...
```
As you can see at the second result I did aligned the connector with another one and it did return `1` as expected.
Let me know if you can't reproduce this or if you think there is any problem.
